services:
  postgres:
    image: postgres:16
    container_name: postgres-users
    ports:
      - 5432:5432
    volumes:
      - postgres-users:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: person
      POSTGRES_PASSWORD: admin

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres-users:
  localstack-users: