spring.application.name=user

#Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

## JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

## Database Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=person
spring.datasource.password=admin

# Amazon SNS
spring.cloud.aws.region.static=us-east-2
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
#spring.cloud.aws.sns.topic.user=arn:aws:sns:us-east-2:963665910885:MyTopic
spring.cloud.aws.sns.topic.user=arn:aws:sns:us-east-2:963665910885:UserEvents

# Prometheus
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.web.server.request.autotime.enabled=true

# Logging
logging.file.name=logs/app.log
logging.level.root=INFO

# Date formatting
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false






